//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FramWorkConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReflectionDemoEntities : DbContext
    {
        public ReflectionDemoEntities()
            : base("name=ReflectionDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FunctionParameter> FunctionParameters { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<TaskFunction> TaskFunctions { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskFunctionParamValue> TaskFunctionParamValues { get; set; }
    }
}
